#!/usr/bin/python

"""Amulet tests on a basic heat deployment on trusty-icehouse."""

from basic_deployment import HeatBasicDeployment

if __name__ == '__main__':
    deployment = HeatBasicDeployment(series='trusty')
    deployment.run_tests()
