#!/usr/bin/python

"""Amulet tests on a basic heat deployment on trusty-juno."""

from basic_deployment import HeatBasicDeployment

if __name__ == '__main__':
    deployment = HeatBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-juno',
                                     source='cloud:trusty-updates/juno')
    deployment.run_tests()
