#!/usr/bin/python

"""Amulet tests on a basic heat deployment on utopic-juno."""

from basic_deployment import HeatBasicDeployment

if __name__ == '__main__':
    deployment = HeatBasicDeployment(series='utopic')
    deployment.run_tests()
