#!/usr/bin/python

"""Amulet tests on a basic heat deployment on vivid-kilo."""

from basic_deployment import HeatBasicDeployment

if __name__ == '__main__':
    deployment = HeatBasicDeployment(series='vivid')
    deployment.run_tests()
