#!/usr/bin/python

"""Amulet tests on a basic heat git deployment on trusty-juno."""

from basic_deployment import HeatBasicDeployment

if __name__ == '__main__':
    deployment = HeatBasicDeployment(series='trusty',
                                     openstack='cloud:trusty-juno',
                                     source='cloud:trusty-updates/juno',
                                     git=True)
    deployment.run_tests()
