#!/bin/bash

set -e

. /root/admin-openrc-v3

openstack domain show heat || {
    openstack domain create --description "Stack projects and users" heat
}

openstack user show heat_domain_admin || {
    openstack user create --domain heat --password `leader-get heat-domain-admin-passwd` heat_domain_admin
}

openstack role add --domain heat --user heat_domain_admin admin || :

openstack role show heat_stack_user || {
    openstack role create heat_stack_user
}
